## 해당 파일은 공용 파일로서, 애플리케이션이 어떤 이름이든 default 프로파일이면 조회된다.
## http://localhost:8888/{config server 의 이름}/default 로 불러올 수 있음
jwt:
  application: user-application

application:
  name: application
  file: application.yml
  profile: default

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/mungmomember?useUnicode=true&characterEncoding=utf8
#    username: mungmo
#    password: 1234
#    driver-class-name: com.mysql.cj.jdbc.Driver